road_signs = {
    "1" : "Ograniczenie prędkości do 20km", 
    "2" : "Ograniczenie prędkości do 30km",
    "3" : "Ograniczenie prędkości do 50km",
    "4" : "Ograniczenie prędkości do 60km",
    "5" : "Ograniczenie prędkości do 70km",
    "6" : "Koniec ograniczenia prędkości do 80km",
    "7" : "Ograniczenie prędkości do 100km",
    "8" : "Ograniczenie prędkości do 120km",
    "9" : "Zakaz wyprzedzania",
    "10" : "Zakaz wjazdu pojazdów o rzeczywistej masie całkowitej ponad 3.5 t",
    "11" : "Pierwszeństwo przejazdu na następnym skrzyżowaniu",
    "12" : "Droga z pierwszeństwem",
    "13" : "Ustąp pierwszeństwa",
    "14" : "Stop",
    "15" : "zakaz wjazdu pojazdów silnikowych",
    "16" : "Zakaz używania pojazdów powyżej 3,5 tony",
    "17" : "Zakaz wjazdu",
    "18" : "Znak ostrozności",
    "19" : "Niebezpieczny zakręt w lewo",
    "20" : "Niebezpieczny zakręt w prawo",
    "21" : "Niebezpieczne zakręty - Podwójna krzyżowa",
    "22" : "Nierówna droga",
    "23" : "Śliska jezdnia",
    "24" : "Zwężenie jezdni - prawostronne",
    "25" : "Roboty na drodze",
    "26" : "Sygnały świetlne",
    "27" : "Przejście dla pieszych",
    "28" : "Dzieci",
    "29" : "Rowerzyści",
    "30" : "Oszronienie jezdni",
    "31" : "Zwierzęta dzikie",
    "32" : "Koniec wszelkich zakazów",
    "33" : "Nakaz jazdy w prawo",
    "34" : "Nakaz jazdy w lewo",
    "35" : "Nakaz jazdy prosto",
    "36" : "Nakaz jazdy prosto lub w prawo",
    "37" : "Nakaz jazdy prosto lub w lewo",
    "38" : "Trzymaj się prawej strony - nakaz jazdy z prawej strony znaku",
    "39" : "Trzymaj się lewej strony - nakaz jazdy z lewej strony znaku",
    "40" : "Ruch okrężny - Rondo obowiązkowe",
    "41" : "Koniec zakazu wyprzedzania",
    "42" : "Koniec zakazu wyprzedzania przez samochody ponad 3.5 tony"
}

